/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ucr.ac.cr.supermercadoacl.vista;

import java.awt.event.ActionListener;
import javax.swing.JOptionPane;

/**
 *
 * @author Axely
 */
public class FRM_Bodega extends javax.swing.JFrame {
    
    public FRM_Bodega() {
        initComponents();
    }
    //--------------------------------------------------------------------------
    
    public static void getMensaje (String mensaje){
        
        JOptionPane.showMessageDialog(null, mensaje);
         
    }
    //--------------------------------------------------------------------------
    
    public PanelDatosProducto getPanelDatos(){
        return this.panelDatosProducto1;
    }
    //--------------------------------------------------------------------------
    
    public void setEscuchadores(ActionListener manejador){
        
        this.panelDatosProducto1.escuchador(manejador);
        
    }
    //--------------------------------------------------------------------------
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelDatosProducto1 = new ucr.ac.cr.supermercadoacl.vista.PanelDatosProducto();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(panelDatosProducto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ucr.ac.cr.supermercadoacl.vista.PanelDatosProducto panelDatosProducto1;
    // End of variables declaration//GEN-END:variables
}
