/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ucr.ac.cr.supermercadoacl.vista;

import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import ucr.ac.cr.supermercadoacl.modelo.Empleado;

/**
 *
 * @author Axely
 */
public class FRM_Menu extends javax.swing.JFrame {

    /**
     * Creates new form FRM_Menu
     */
    public FRM_Menu() {
        initComponents();
    }
    //--------------------------------------------------------------------------
    
    public static void getMensaje (String mensaje){
        
        JOptionPane.showMessageDialog(null, mensaje);
        
    }
    //--------------------------------------------------------------------------
    public Empleado inicioSesion (){
        
        return new Empleado(this.jtUsuario.getText(), String.valueOf(this.jpClave.getPassword()));
        
    }
    //--------------------------------------------------------------------------
    
    //Va recibir un true si quiere cerrar sesion
    public void cerrarSesion (boolean estado){
        
        this.jtUsuario.setText("");
        this.jpClave.setText("");
        
        this.loginGerente(!estado);
    }
    //--------------------------------------------------------------------------
    
    public void loginGerente (boolean estado){
        
        this.jmiEmpleados.setEnabled(estado);
        this.loginSubGerente(estado);
    }
    //--------------------------------------------------------------------------
    
    public void loginSubGerente (boolean estado){
        
        this.jmiBodega.setEnabled(estado);
        this.loginCajero(estado);
    }
    //--------------------------------------------------------------------------
    
    public void loginCajero (boolean estado){
        
        this.jmiFacturas.setEnabled(estado);
        this.jtUsuario.setEditable(!estado);
        this.jpClave.setEditable(!estado);
        this.jbCerrar.setEnabled(estado);
        this.jbIniciar.setEnabled(!estado);
    }
    //--------------------------------------------------------------------------
    
    public void setEscuchadores (ActionListener manejador){
        
        this.jmiBodega.addActionListener(manejador);
        this.jmiEmpleados.addActionListener(manejador);
        this.jmiFacturas.addActionListener(manejador);
        this.jmiSalir.addActionListener(manejador);
        this.jbCerrar.addActionListener(manejador);
        this.jbIniciar.addActionListener(manejador);
        this.jmiCreditos.addActionListener(manejador);
    }
    //--------------------------------------------------------------------------
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jbIniciar = new javax.swing.JButton();
        jbCerrar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtUsuario = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jpClave = new javax.swing.JPasswordField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmiEmpleados = new javax.swing.JMenuItem();
        jmiBodega = new javax.swing.JMenuItem();
        jmiFacturas = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jmiSalir = new javax.swing.JMenuItem();
        jmiCreditos = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbIniciar.setText("Iniciar Sesión");
        jbIniciar.setActionCommand("IniciarSesion");
        jbIniciar.setPreferredSize(new java.awt.Dimension(99, 26));
        jPanel1.add(jbIniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(419, 370, 120, -1));

        jbCerrar.setText("Cerrar Sesión");
        jbCerrar.setActionCommand("CerrarSesion");
        jbCerrar.setEnabled(false);
        jbCerrar.setPreferredSize(new java.awt.Dimension(99, 26));
        jPanel1.add(jbCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(419, 330, 120, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel2.setText("Usuario:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel3.setText("Clave:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, -1, -1));

        jtUsuario.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jtUsuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(jtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, 290, 26));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Login.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 320));

        jpClave.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jpClave.setMinimumSize(new java.awt.Dimension(64, 26));
        jPanel1.add(jpClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 370, 290, 26));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 419));

        jMenu1.setText("File");

        jmiEmpleados.setText("Empleados");
        jmiEmpleados.setEnabled(false);
        jMenu1.add(jmiEmpleados);

        jmiBodega.setText("Bodega");
        jmiBodega.setEnabled(false);
        jMenu1.add(jmiBodega);

        jmiFacturas.setText("Caja");
        jmiFacturas.setEnabled(false);
        jMenu1.add(jmiFacturas);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");

        jmiSalir.setText("Salir");
        jMenu2.add(jmiSalir);

        jmiCreditos.setText("Créditos");
        jmiCreditos.setActionCommand("Creditos");
        jMenu2.add(jmiCreditos);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbCerrar;
    private javax.swing.JButton jbIniciar;
    private javax.swing.JMenuItem jmiBodega;
    private javax.swing.JMenuItem jmiCreditos;
    private javax.swing.JMenuItem jmiEmpleados;
    private javax.swing.JMenuItem jmiFacturas;
    private javax.swing.JMenuItem jmiSalir;
    private javax.swing.JPasswordField jpClave;
    private javax.swing.JTextField jtUsuario;
    // End of variables declaration//GEN-END:variables
}
