/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ucr.ac.cr.supermercadoacl.vista;

import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import ucr.ac.cr.supermercadoacl.modelo.Empleado;

/**
 *
 * @author Axely
 */
public class PanelDatosEmpleado extends javax.swing.JPanel {

    /**
     * Creates new form PanelDatosEmpleado
     */
    public PanelDatosEmpleado() {
        initComponents();
    }
    //--------------------------------------------------------------------------
    
    //Extraer los JTextField
    public Empleado getEmpleado (){
        
        if (this.verificarCampos()!=true){
            return new Empleado(this.jtUsuario.getText(), this.jtClave.getText(),
                this.jtNombre.getText(), this.jcPuesto.getSelectedItem().toString(),
                Integer.parseInt(this.jtCedula.getText()), 
                Integer.parseInt(this.jtEdad.getText()));
        }
        
        return null;
    }
    //--------------------------------------------------------------------------
    
    //Rellenar los JTextField
    public void setEmpleado (Empleado empleado){
        
        this.jtUsuario.setText(empleado.getUsuario());
        this.jtClave.setText(empleado.getClave());
        this.jtNombre.setText(empleado.getNombreEmpleado());
        this.jcPuesto.setSelectedItem(empleado.getPuesto());
        this.jtCedula.setText(""+empleado.getCedula());
        this.jtEdad.setText(""+empleado.getEdad());
        
    }
    //--------------------------------------------------------------------------
    
    //Limpiar los JTextField
    public void limpiarCampos (){
        
        this.jtUsuario.setText("");
        this.jtClave.setText("");
        this.jtNombre.setText("");
        this.jcPuesto.setSelectedIndex(0);
        this.jtCedula.setText("");
        this.jtEdad.setText("");
        
    }
    //--------------------------------------------------------------------------
    
    //Activar o desactivar botones despues de una accion
    public void activarBotones (boolean estado){
        
        this.jbEditar.setEnabled(estado);
        this.jbEliminar.setEnabled(estado);
        
    }
    //--------------------------------------------------------------------------
    
    //ActionListener de los botones
    public void escuchador (ActionListener manejador){
        
        this.jbRegistrar.addActionListener(manejador);
        this.jbEditar.addActionListener(manejador);
        this.jbEliminar.addActionListener(manejador);
        this.jcPuesto.addActionListener(manejador);
        this.jbReporte.addActionListener(manejador);
        this.jbCerrar.addActionListener(manejador);
        
    }
    //--------------------------------------------------------------------------
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbRegistrar = new javax.swing.JButton();
        jbEditar = new javax.swing.JButton();
        jbEliminar = new javax.swing.JButton();
        jbCerrar = new javax.swing.JButton();
        jbReporte = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtUsuario = new javax.swing.JTextField();
        jtClave = new javax.swing.JTextField();
        jtNombre = new javax.swing.JTextField();
        jtCedula = new javax.swing.JTextField();
        jtEdad = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jcPuesto = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbRegistrar.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jbRegistrar.setForeground(new java.awt.Color(51, 51, 51));
        jbRegistrar.setText("Registrar");
        add(jbRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 363, 110, 30));

        jbEditar.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jbEditar.setForeground(new java.awt.Color(51, 51, 51));
        jbEditar.setText("Editar");
        jbEditar.setEnabled(false);
        add(jbEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 363, 110, 30));

        jbEliminar.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jbEliminar.setForeground(new java.awt.Color(51, 51, 51));
        jbEliminar.setText("Eliminar");
        jbEliminar.setEnabled(false);
        add(jbEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 363, 110, 30));

        jbCerrar.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jbCerrar.setForeground(new java.awt.Color(51, 51, 51));
        jbCerrar.setText("Cerrar");
        add(jbCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, 70, -1));

        jbReporte.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jbReporte.setForeground(new java.awt.Color(51, 51, 51));
        jbReporte.setText("Reporte");
        add(jbReporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 363, 110, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Registro Empleado");
        jLabel1.setToolTipText("");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Usuario:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Clave:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Nombre:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Cedula:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Puesto:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, -1, -1));

        jtUsuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        add(jtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 290, 30));

        jtClave.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        add(jtClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 290, 30));

        jtNombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        add(jtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 290, 30));

        jtCedula.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        add(jtCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 290, 30));

        jtEdad.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        add(jtEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, 290, 30));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("Edad:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, -1));

        jcPuesto.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jcPuesto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SubGerente", "Cajero" }));
        jcPuesto.setPreferredSize(new java.awt.Dimension(72, 30));
        add(jcPuesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, 290, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fondoEmpleados.png"))); // NOI18N
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, -1));
    }// </editor-fold>//GEN-END:initComponents
    public boolean verificarCampos (){
        
        try {

            // Obtener los textos y valores necesarios
            if (this.jtCedula.getText().isEmpty() || this.jtClave.getText().isEmpty() ||
                this.jtEdad.getText().isEmpty() || this.jtNombre.getText().isEmpty() ||
                this.jtUsuario.getText().isEmpty()){
                
                throw new NullPointerException("Hay espacios por rellenar");
                
            }
            
            //Try-Catch para verificar si hay caracteres no validos
            try {
                
                Double.parseDouble(this.jtCedula.getText()); 
                Double.parseDouble(this.jtEdad.getText());
                
            } catch (NumberFormatException e) {
            
                JOptionPane.showMessageDialog(null, 
                    "Error: Digite un valor numerico en los campos correspondientes");
                return true;
            }
                
        } catch (NullPointerException e) {

            // Manejar la excepción de campos nulos
            JOptionPane.showMessageDialog(null, "Error: " + e.getMessage()); 
            // Aquí podrías manejar el error de otra forma, como mostrar un mensaje al usuario
            return true;

        }
        
        return false;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JButton jbCerrar;
    private javax.swing.JButton jbEditar;
    private javax.swing.JButton jbEliminar;
    private javax.swing.JButton jbRegistrar;
    private javax.swing.JButton jbReporte;
    private javax.swing.JComboBox<String> jcPuesto;
    private javax.swing.JTextField jtCedula;
    private javax.swing.JTextField jtClave;
    private javax.swing.JTextField jtEdad;
    private javax.swing.JTextField jtNombre;
    private javax.swing.JTextField jtUsuario;
    // End of variables declaration//GEN-END:variables
}
